apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: go_sample_app
  namespace: flux-system
spec:
  image: artamevia/go_sample_app
  interval: 30s
  secretRef:
    name: dockerhub-key

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go_sample_app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go_sample_app
  policy:
    semver:
      range: '>=0.0.1'

---
apiVersion: v1
kind: Secret
metadata:
  name: go_sample_app-configs
  namespace: playground-dfgjkt
type: Opaque
stringData:
  APP_NAME: "your_ip"
  ENV: "production"
  PORT: "3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_sample_app
  namespace: playground-dfgjkt
  labels:
    app: go_sample_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go_sample_app
  template:
    metadata:
      labels:
        app: go_sample_app
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: go_sample_app
          image: artamevia/go_sample_app:1.0.2
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: "go_sample_app-configs"

---
apiVersion: v1
kind: Service
metadata:
  name: go_sample_app
  namespace: playground-dfgjkt
  labels:
    app: go_sample_app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: go_sample_app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go_sample_app
  namespace: playground-dfgjkt
spec:
  rules:
    - host: ipinfo.dwyor.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go_sample_app
                port:
                  number: 80
  ingressClassName: traefik
